### ISSUE TITLE
Is `app.use(bodyParser.json())` used/needed?

### ISSUE THREAD

**Issue by davidpmccormick** [MoonHighway/ski-dictionary#1]
I can't see what benefit [line 22 in app-server.js](https://github.com/MoonHighway/ski-dictionary/blob/master/app-server.js#L22) brings. If I remove it, everything (seems to) work for me. Could you explain if I've missed something, or when `app.use(bodyParser.json())` would become useful/necessary?

Excellent course, btw.

**Comment by MoonTahoe** [comment]
Sometimes request bodies are URL encoded: `foo=bar&gnar=gnarly`,
Other times they are encoded as JSON: `{ "foo": "bar", "gnar": "gnarley" }`

The `bodyParser` has middleware for parsing both types of request bodies:

``` javascript
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: false }));
```

Typically our services are used by all types of clients and developers, so parsing for both types of request bodies just ensures that your service will work.
